/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC2771Recipient } from "./IERC2771Recipient";
export type { IPaymaster } from "./IPaymaster";
export type { IRelayHub } from "./IRelayHub";
export type { IStakeManager } from "./IStakeManager";
