/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace IStakeManager {
  export type AbandonedRelayServerConfigStruct = {
    devAddress: PromiseOrValue<string>;
    abandonmentDelay: PromiseOrValue<BigNumberish>;
    escheatmentDelay: PromiseOrValue<BigNumberish>;
  };

  export type AbandonedRelayServerConfigStructOutput = [
    string,
    BigNumber,
    BigNumber
  ] & {
    devAddress: string;
    abandonmentDelay: BigNumber;
    escheatmentDelay: BigNumber;
  };

  export type StakeInfoStruct = {
    stake: PromiseOrValue<BigNumberish>;
    unstakeDelay: PromiseOrValue<BigNumberish>;
    withdrawTime: PromiseOrValue<BigNumberish>;
    abandonedTime: PromiseOrValue<BigNumberish>;
    keepaliveTime: PromiseOrValue<BigNumberish>;
    token: PromiseOrValue<string>;
    owner: PromiseOrValue<string>;
  };

  export type StakeInfoStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    string,
    string
  ] & {
    stake: BigNumber;
    unstakeDelay: BigNumber;
    withdrawTime: BigNumber;
    abandonedTime: BigNumber;
    keepaliveTime: BigNumber;
    token: string;
    owner: string;
  };
}

export interface IStakeManagerInterface extends utils.Interface {
  functions: {
    "authorizeHubByManager(address)": FunctionFragment;
    "authorizeHubByOwner(address,address)": FunctionFragment;
    "escheatAbandonedRelayStake(address)": FunctionFragment;
    "getAbandonedRelayServerConfig()": FunctionFragment;
    "getBurnAddress()": FunctionFragment;
    "getCreationBlock()": FunctionFragment;
    "getMaxUnstakeDelay()": FunctionFragment;
    "getStakeInfo(address)": FunctionFragment;
    "isRelayEscheatable(address)": FunctionFragment;
    "markRelayAbandoned(address)": FunctionFragment;
    "penalizeRelayManager(address,address,uint256)": FunctionFragment;
    "setBurnAddress(address)": FunctionFragment;
    "setDevAddress(address)": FunctionFragment;
    "setRelayManagerOwner(address)": FunctionFragment;
    "stakeForRelayManager(address,address,uint256,uint256)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "unauthorizeHubByManager(address)": FunctionFragment;
    "unauthorizeHubByOwner(address,address)": FunctionFragment;
    "unlockStake(address)": FunctionFragment;
    "updateRelayKeepaliveTime(address)": FunctionFragment;
    "versionSM()": FunctionFragment;
    "withdrawStake(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "authorizeHubByManager"
      | "authorizeHubByOwner"
      | "escheatAbandonedRelayStake"
      | "getAbandonedRelayServerConfig"
      | "getBurnAddress"
      | "getCreationBlock"
      | "getMaxUnstakeDelay"
      | "getStakeInfo"
      | "isRelayEscheatable"
      | "markRelayAbandoned"
      | "penalizeRelayManager"
      | "setBurnAddress"
      | "setDevAddress"
      | "setRelayManagerOwner"
      | "stakeForRelayManager"
      | "supportsInterface"
      | "unauthorizeHubByManager"
      | "unauthorizeHubByOwner"
      | "unlockStake"
      | "updateRelayKeepaliveTime"
      | "versionSM"
      | "withdrawStake"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "authorizeHubByManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeHubByOwner",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "escheatAbandonedRelayStake",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAbandonedRelayServerConfig",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBurnAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCreationBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxUnstakeDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStakeInfo",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isRelayEscheatable",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "markRelayAbandoned",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "penalizeRelayManager",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setBurnAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setDevAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRelayManagerOwner",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeForRelayManager",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "unauthorizeHubByManager",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unauthorizeHubByOwner",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockStake",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRelayKeepaliveTime",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "versionSM", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdrawStake",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeHubByManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeHubByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escheatAbandonedRelayStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAbandonedRelayServerConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBurnAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreationBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxUnstakeDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStakeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRelayEscheatable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markRelayAbandoned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "penalizeRelayManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBurnAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDevAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRelayManagerOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeForRelayManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unauthorizeHubByManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unauthorizeHubByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRelayKeepaliveTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "versionSM", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStake",
    data: BytesLike
  ): Result;

  events: {
    "AbandonedRelayManagerStakeEscheated(address,address,address,uint256)": EventFragment;
    "BurnAddressSet(address)": EventFragment;
    "DevAddressSet(address)": EventFragment;
    "HubAuthorized(address,address)": EventFragment;
    "HubUnauthorized(address,address,uint256)": EventFragment;
    "OwnerSet(address,address)": EventFragment;
    "RelayServerAbandoned(address,uint256)": EventFragment;
    "RelayServerKeepalive(address,uint256)": EventFragment;
    "StakeAdded(address,address,address,uint256,uint256)": EventFragment;
    "StakePenalized(address,address,address,uint256)": EventFragment;
    "StakeUnlocked(address,address,uint256)": EventFragment;
    "StakeWithdrawn(address,address,address,uint256)": EventFragment;
  };

  getEvent(
    nameOrSignatureOrTopic: "AbandonedRelayManagerStakeEscheated"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BurnAddressSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DevAddressSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HubAuthorized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "HubUnauthorized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnerSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayServerAbandoned"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelayServerKeepalive"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakePenalized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeUnlocked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "StakeWithdrawn"): EventFragment;
}

export interface AbandonedRelayManagerStakeEscheatedEventObject {
  relayManager: string;
  owner: string;
  token: string;
  amount: BigNumber;
}
export type AbandonedRelayManagerStakeEscheatedEvent = TypedEvent<
  [string, string, string, BigNumber],
  AbandonedRelayManagerStakeEscheatedEventObject
>;

export type AbandonedRelayManagerStakeEscheatedEventFilter =
  TypedEventFilter<AbandonedRelayManagerStakeEscheatedEvent>;

export interface BurnAddressSetEventObject {
  burnAddress: string;
}
export type BurnAddressSetEvent = TypedEvent<
  [string],
  BurnAddressSetEventObject
>;

export type BurnAddressSetEventFilter = TypedEventFilter<BurnAddressSetEvent>;

export interface DevAddressSetEventObject {
  devAddress: string;
}
export type DevAddressSetEvent = TypedEvent<[string], DevAddressSetEventObject>;

export type DevAddressSetEventFilter = TypedEventFilter<DevAddressSetEvent>;

export interface HubAuthorizedEventObject {
  relayManager: string;
  relayHub: string;
}
export type HubAuthorizedEvent = TypedEvent<
  [string, string],
  HubAuthorizedEventObject
>;

export type HubAuthorizedEventFilter = TypedEventFilter<HubAuthorizedEvent>;

export interface HubUnauthorizedEventObject {
  relayManager: string;
  relayHub: string;
  removalTime: BigNumber;
}
export type HubUnauthorizedEvent = TypedEvent<
  [string, string, BigNumber],
  HubUnauthorizedEventObject
>;

export type HubUnauthorizedEventFilter = TypedEventFilter<HubUnauthorizedEvent>;

export interface OwnerSetEventObject {
  relayManager: string;
  owner: string;
}
export type OwnerSetEvent = TypedEvent<[string, string], OwnerSetEventObject>;

export type OwnerSetEventFilter = TypedEventFilter<OwnerSetEvent>;

export interface RelayServerAbandonedEventObject {
  relayManager: string;
  abandonedTime: BigNumber;
}
export type RelayServerAbandonedEvent = TypedEvent<
  [string, BigNumber],
  RelayServerAbandonedEventObject
>;

export type RelayServerAbandonedEventFilter =
  TypedEventFilter<RelayServerAbandonedEvent>;

export interface RelayServerKeepaliveEventObject {
  relayManager: string;
  keepaliveTime: BigNumber;
}
export type RelayServerKeepaliveEvent = TypedEvent<
  [string, BigNumber],
  RelayServerKeepaliveEventObject
>;

export type RelayServerKeepaliveEventFilter =
  TypedEventFilter<RelayServerKeepaliveEvent>;

export interface StakeAddedEventObject {
  relayManager: string;
  owner: string;
  token: string;
  stake: BigNumber;
  unstakeDelay: BigNumber;
}
export type StakeAddedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber],
  StakeAddedEventObject
>;

export type StakeAddedEventFilter = TypedEventFilter<StakeAddedEvent>;

export interface StakePenalizedEventObject {
  relayManager: string;
  beneficiary: string;
  token: string;
  reward: BigNumber;
}
export type StakePenalizedEvent = TypedEvent<
  [string, string, string, BigNumber],
  StakePenalizedEventObject
>;

export type StakePenalizedEventFilter = TypedEventFilter<StakePenalizedEvent>;

export interface StakeUnlockedEventObject {
  relayManager: string;
  owner: string;
  withdrawTime: BigNumber;
}
export type StakeUnlockedEvent = TypedEvent<
  [string, string, BigNumber],
  StakeUnlockedEventObject
>;

export type StakeUnlockedEventFilter = TypedEventFilter<StakeUnlockedEvent>;

export interface StakeWithdrawnEventObject {
  relayManager: string;
  owner: string;
  token: string;
  amount: BigNumber;
}
export type StakeWithdrawnEvent = TypedEvent<
  [string, string, string, BigNumber],
  StakeWithdrawnEventObject
>;

export type StakeWithdrawnEventFilter = TypedEventFilter<StakeWithdrawnEvent>;

export interface IStakeManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IStakeManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    authorizeHubByManager(
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    authorizeHubByOwner(
      relayManager: PromiseOrValue<string>,
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    escheatAbandonedRelayStake(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getAbandonedRelayServerConfig(
      overrides?: CallOverrides
    ): Promise<[IStakeManager.AbandonedRelayServerConfigStructOutput]>;

    getBurnAddress(overrides?: CallOverrides): Promise<[string]>;

    getCreationBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    getMaxUnstakeDelay(overrides?: CallOverrides): Promise<[BigNumber]>;

    getStakeInfo(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [IStakeManager.StakeInfoStructOutput, boolean] & {
        stakeInfo: IStakeManager.StakeInfoStructOutput;
        isSenderAuthorizedHub: boolean;
      }
    >;

    isRelayEscheatable(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    markRelayAbandoned(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    penalizeRelayManager(
      relayManager: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBurnAddress(
      _burnAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setDevAddress(
      _burnAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRelayManagerOwner(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stakeForRelayManager(
      token: PromiseOrValue<string>,
      relayManager: PromiseOrValue<string>,
      unstakeDelay: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    unauthorizeHubByManager(
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unauthorizeHubByOwner(
      relayManager: PromiseOrValue<string>,
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    unlockStake(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateRelayKeepaliveTime(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    versionSM(overrides?: CallOverrides): Promise<[string]>;

    withdrawStake(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  authorizeHubByManager(
    relayHub: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  authorizeHubByOwner(
    relayManager: PromiseOrValue<string>,
    relayHub: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  escheatAbandonedRelayStake(
    relayManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getAbandonedRelayServerConfig(
    overrides?: CallOverrides
  ): Promise<IStakeManager.AbandonedRelayServerConfigStructOutput>;

  getBurnAddress(overrides?: CallOverrides): Promise<string>;

  getCreationBlock(overrides?: CallOverrides): Promise<BigNumber>;

  getMaxUnstakeDelay(overrides?: CallOverrides): Promise<BigNumber>;

  getStakeInfo(
    relayManager: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<
    [IStakeManager.StakeInfoStructOutput, boolean] & {
      stakeInfo: IStakeManager.StakeInfoStructOutput;
      isSenderAuthorizedHub: boolean;
    }
  >;

  isRelayEscheatable(
    relayManager: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  markRelayAbandoned(
    relayManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  penalizeRelayManager(
    relayManager: PromiseOrValue<string>,
    beneficiary: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBurnAddress(
    _burnAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setDevAddress(
    _burnAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRelayManagerOwner(
    owner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stakeForRelayManager(
    token: PromiseOrValue<string>,
    relayManager: PromiseOrValue<string>,
    unstakeDelay: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  unauthorizeHubByManager(
    relayHub: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unauthorizeHubByOwner(
    relayManager: PromiseOrValue<string>,
    relayHub: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  unlockStake(
    relayManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateRelayKeepaliveTime(
    relayManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  versionSM(overrides?: CallOverrides): Promise<string>;

  withdrawStake(
    relayManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    authorizeHubByManager(
      relayHub: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    authorizeHubByOwner(
      relayManager: PromiseOrValue<string>,
      relayHub: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    escheatAbandonedRelayStake(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getAbandonedRelayServerConfig(
      overrides?: CallOverrides
    ): Promise<IStakeManager.AbandonedRelayServerConfigStructOutput>;

    getBurnAddress(overrides?: CallOverrides): Promise<string>;

    getCreationBlock(overrides?: CallOverrides): Promise<BigNumber>;

    getMaxUnstakeDelay(overrides?: CallOverrides): Promise<BigNumber>;

    getStakeInfo(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<
      [IStakeManager.StakeInfoStructOutput, boolean] & {
        stakeInfo: IStakeManager.StakeInfoStructOutput;
        isSenderAuthorizedHub: boolean;
      }
    >;

    isRelayEscheatable(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    markRelayAbandoned(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    penalizeRelayManager(
      relayManager: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setBurnAddress(
      _burnAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setDevAddress(
      _burnAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRelayManagerOwner(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    stakeForRelayManager(
      token: PromiseOrValue<string>,
      relayManager: PromiseOrValue<string>,
      unstakeDelay: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    unauthorizeHubByManager(
      relayHub: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unauthorizeHubByOwner(
      relayManager: PromiseOrValue<string>,
      relayHub: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    unlockStake(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRelayKeepaliveTime(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    versionSM(overrides?: CallOverrides): Promise<string>;

    withdrawStake(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AbandonedRelayManagerStakeEscheated(address,address,address,uint256)"(
      relayManager?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null
    ): AbandonedRelayManagerStakeEscheatedEventFilter;
    AbandonedRelayManagerStakeEscheated(
      relayManager?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null
    ): AbandonedRelayManagerStakeEscheatedEventFilter;

    "BurnAddressSet(address)"(
      burnAddress?: PromiseOrValue<string> | null
    ): BurnAddressSetEventFilter;
    BurnAddressSet(
      burnAddress?: PromiseOrValue<string> | null
    ): BurnAddressSetEventFilter;

    "DevAddressSet(address)"(
      devAddress?: PromiseOrValue<string> | null
    ): DevAddressSetEventFilter;
    DevAddressSet(
      devAddress?: PromiseOrValue<string> | null
    ): DevAddressSetEventFilter;

    "HubAuthorized(address,address)"(
      relayManager?: PromiseOrValue<string> | null,
      relayHub?: PromiseOrValue<string> | null
    ): HubAuthorizedEventFilter;
    HubAuthorized(
      relayManager?: PromiseOrValue<string> | null,
      relayHub?: PromiseOrValue<string> | null
    ): HubAuthorizedEventFilter;

    "HubUnauthorized(address,address,uint256)"(
      relayManager?: PromiseOrValue<string> | null,
      relayHub?: PromiseOrValue<string> | null,
      removalTime?: null
    ): HubUnauthorizedEventFilter;
    HubUnauthorized(
      relayManager?: PromiseOrValue<string> | null,
      relayHub?: PromiseOrValue<string> | null,
      removalTime?: null
    ): HubUnauthorizedEventFilter;

    "OwnerSet(address,address)"(
      relayManager?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null
    ): OwnerSetEventFilter;
    OwnerSet(
      relayManager?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null
    ): OwnerSetEventFilter;

    "RelayServerAbandoned(address,uint256)"(
      relayManager?: PromiseOrValue<string> | null,
      abandonedTime?: null
    ): RelayServerAbandonedEventFilter;
    RelayServerAbandoned(
      relayManager?: PromiseOrValue<string> | null,
      abandonedTime?: null
    ): RelayServerAbandonedEventFilter;

    "RelayServerKeepalive(address,uint256)"(
      relayManager?: PromiseOrValue<string> | null,
      keepaliveTime?: null
    ): RelayServerKeepaliveEventFilter;
    RelayServerKeepalive(
      relayManager?: PromiseOrValue<string> | null,
      keepaliveTime?: null
    ): RelayServerKeepaliveEventFilter;

    "StakeAdded(address,address,address,uint256,uint256)"(
      relayManager?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      token?: null,
      stake?: null,
      unstakeDelay?: null
    ): StakeAddedEventFilter;
    StakeAdded(
      relayManager?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      token?: null,
      stake?: null,
      unstakeDelay?: null
    ): StakeAddedEventFilter;

    "StakePenalized(address,address,address,uint256)"(
      relayManager?: PromiseOrValue<string> | null,
      beneficiary?: PromiseOrValue<string> | null,
      token?: null,
      reward?: null
    ): StakePenalizedEventFilter;
    StakePenalized(
      relayManager?: PromiseOrValue<string> | null,
      beneficiary?: PromiseOrValue<string> | null,
      token?: null,
      reward?: null
    ): StakePenalizedEventFilter;

    "StakeUnlocked(address,address,uint256)"(
      relayManager?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      withdrawTime?: null
    ): StakeUnlockedEventFilter;
    StakeUnlocked(
      relayManager?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      withdrawTime?: null
    ): StakeUnlockedEventFilter;

    "StakeWithdrawn(address,address,address,uint256)"(
      relayManager?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null
    ): StakeWithdrawnEventFilter;
    StakeWithdrawn(
      relayManager?: PromiseOrValue<string> | null,
      owner?: PromiseOrValue<string> | null,
      token?: null,
      amount?: null
    ): StakeWithdrawnEventFilter;
  };

  estimateGas: {
    authorizeHubByManager(
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    authorizeHubByOwner(
      relayManager: PromiseOrValue<string>,
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    escheatAbandonedRelayStake(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getAbandonedRelayServerConfig(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBurnAddress(overrides?: CallOverrides): Promise<BigNumber>;

    getCreationBlock(overrides?: CallOverrides): Promise<BigNumber>;

    getMaxUnstakeDelay(overrides?: CallOverrides): Promise<BigNumber>;

    getStakeInfo(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRelayEscheatable(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    markRelayAbandoned(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    penalizeRelayManager(
      relayManager: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBurnAddress(
      _burnAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setDevAddress(
      _burnAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRelayManagerOwner(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stakeForRelayManager(
      token: PromiseOrValue<string>,
      relayManager: PromiseOrValue<string>,
      unstakeDelay: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unauthorizeHubByManager(
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unauthorizeHubByOwner(
      relayManager: PromiseOrValue<string>,
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    unlockStake(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateRelayKeepaliveTime(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    versionSM(overrides?: CallOverrides): Promise<BigNumber>;

    withdrawStake(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    authorizeHubByManager(
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    authorizeHubByOwner(
      relayManager: PromiseOrValue<string>,
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    escheatAbandonedRelayStake(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getAbandonedRelayServerConfig(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBurnAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCreationBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMaxUnstakeDelay(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStakeInfo(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRelayEscheatable(
      relayManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    markRelayAbandoned(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    penalizeRelayManager(
      relayManager: PromiseOrValue<string>,
      beneficiary: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBurnAddress(
      _burnAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setDevAddress(
      _burnAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRelayManagerOwner(
      owner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stakeForRelayManager(
      token: PromiseOrValue<string>,
      relayManager: PromiseOrValue<string>,
      unstakeDelay: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unauthorizeHubByManager(
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unauthorizeHubByOwner(
      relayManager: PromiseOrValue<string>,
      relayHub: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    unlockStake(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateRelayKeepaliveTime(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    versionSM(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    withdrawStake(
      relayManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
