//This code was auto generated using shipr.dev 

import React, { useState, useEffect } from 'react'
export default function index() {




  return (<div className=' w-full min-h-screen bg-white'>
            <header className=' '>
              <div className='container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center '>
                <a className='flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0 '>
                  <svg
                       xmlns='http://www.w3.org/2000/svg'
                       fill='none'
                       stroke='currentColor'
                       strokeLinecap='round'
                       strokeLinejoin='round'
                       strokeWidth='2'
                       viewBox='0 0 24 24'
                       className='w-10 h-10 text-white p-2 bg-indigo-500 rounded-full '
                  >
                    <path
                          d='M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5'
                          className=' '
                    ></path>
                  </svg> <span className='ml-3 text-xl '>GPN</span></a>
                <nav className='md:ml-auto flex flex-wrap items-center text-base justify-center '>
                  <a className='mr-5 hover:text-gray-900 '>demo</a> <a className='mr-5 hover:text-gray-900 '>sign in</a>
                </nav>
                <button className='inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0 '>
                  Sign Up
                  <svg
                       fill='none'
                       stroke='currentColor'
                       strokeLinecap='round'
                       strokeLinejoin='round'
                       strokeWidth='2'
                       viewBox='0 0 24 24'
                       className='w-4 h-4 ml-1 '
                  >
                    <path
                          d='M5 12h14M12 5l7 7-7 7'
                          className=' '
                    ></path>
                  </svg>
                </button>
              </div>
            </header>
             
            <section className=' '>
              <div className='container mx-auto flex px-5 py-24 items-center justify-center flex-col '>
                <img
                     alt='hero'
                     src='https://dummyimage.com/300'
                     className='lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded '
                ></img>
                <div className='text-center lg:w-2/3 w-full '>
                  <h1 className='title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900 '>GPN</h1>
                  <p className='mb-8 leading-relaxed '>
                    Welcome to GPN
                  </p>
                  <div className='flex justify-center '>
                    <button className='inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg '>
                      Button
                    </button>
                    <button className='ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg '>
                      Button
                    </button>
                  </div>
                </div>
              </div>
            </section>
            <footer className=' '>
              <div className='container px-5 py-8 mx-auto flex items-center sm:flex-row flex-col '>
                <a className='flex title-font font-medium items-center md:justify-start justify-center text-gray-900 '>
                  <svg
                       xmlns='http://www.w3.org/2000/svg'
                       fill='none'
                       stroke='currentColor'
                       strokeLinecap='round'
                       strokeLinejoin='round'
                       strokeWidth='2'
                       viewBox='0 0 24 24'
                       className='w-10 h-10 text-white p-2 bg-indigo-500 rounded-full '
                  >
                    <path
                          d='M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5'
                          className=' '
                    ></path>
                  </svg> <span className='ml-3 text-xl '>GSN</span></a>
                <p className='text-sm text-gray-500 sm:ml-4 sm:pl-4 sm:border-l-2 sm:border-gray-200 sm:py-2 sm:mt-0 mt-4 '>
                Gas Pass Network
                </p> <span className='inline-flex sm:ml-auto sm:mt-0 mt-4 justify-center sm:justify-start '><a className='text-gray-500 '><svg
                                                                                                                                               fill='currentColor'
                                                                                                                                               strokeLinecap='round'
                                                                                                                                               strokeLinejoin='round'
                                                                                                                                               strokeWidth='2'
                                                                                                                                               viewBox='0 0 24 24'
                                                                                                                                               className='w-5 h-5 '
                                                                                                                                          > <path
                                                                                                                                                                                                                                                                                d='M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z'
                                                                                                                                                                                                                                                                                className=' '
                                                                                                                                                                                                                                                                          ></path> </svg></a> <a className='ml-3 text-gray-500 '><svg
                                                                                                                                                                                                                                                                                                                                                                                                                            fill='currentColor'
                                                                                                                                                                                                                                                                                                                                                                                                                            strokeLinecap='round'
                                                                                                                                                                                                                                                                                                                                                                                                                            strokeLinejoin='round'
                                                                                                                                                                                                                                                                                                                                                                                                                            strokeWidth='2'
                                                                                                                                                                                                                                                                                                                                                                                                                            viewBox='0 0 24 24'
                                                                                                                                                                                                                                                                                                                                                                                                                            className='w-5 h-5 '
                                                                                                                                                                                                                                                                                                                                                                                                                       > <path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             d='M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             className=' '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ></path> </svg></a> <a className='ml-3 text-gray-500 '><svg
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fill='none'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              stroke='currentColor'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              strokeLinecap='round'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              strokeLinejoin='round'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              strokeWidth='2'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              viewBox='0 0 24 24'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              className='w-5 h-5 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         > <rect
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             width='20'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             height='20'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             x='2'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             y='2'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             rx='5'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ry='5'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             className=' '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       > undefined </rect> <path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     d='M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37zm1.5-4.87h.01'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     className=' '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ></path> </svg></a> <a className='ml-3 text-gray-500 '><svg
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           fill='currentColor'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           stroke='currentColor'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           strokeLinecap='round'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           strokeLinejoin='round'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           strokeWidth='0'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           viewBox='0 0 24 24'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           className='w-5 h-5 '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      > <path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  stroke='none'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  d='M16 8a6 6 0 016 6v7h-4v-7a2 2 0 00-2-2 2 2 0 00-2 2v7h-4v-7a6 6 0 016-6zM2 9h4v12H2z'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className=' '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ></path> <circle
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       cx='4'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       cy='4'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       r='2'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       stroke='none'
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       className=' '
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ></circle> </svg></a></span>
              </div>
            </footer>
          </div>)
}