/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as paymasterSol from "./Paymaster.sol";
export type { paymasterSol };
import type * as recepientSol from "./Recepient.sol";
export type { recepientSol };
export type { NumericalStorage } from "./NumericalStorage";
