/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ERC2771Recipient,
  ERC2771RecipientInterface,
} from "../../../../@opengsn/contracts/src/ERC2771Recipient";

const _abi = [
  {
    inputs: [],
    name: "getTrustedForwarder",
    outputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "forwarder",
        type: "address",
      },
    ],
    name: "isTrustedForwarder",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ERC2771Recipient__factory {
  static readonly abi = _abi;
  static createInterface(): ERC2771RecipientInterface {
    return new utils.Interface(_abi) as ERC2771RecipientInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC2771Recipient {
    return new Contract(address, _abi, signerOrProvider) as ERC2771Recipient;
  }
}
